#ifndef CONSTANTS_H
#define CONSTANTS_h

#define WIN_WID 960
#define WIN_HEI 540
#define COLORS {RED, YELLOW, BLUE, GREEN}
#define SHIP_RADIUS 10.0f
#define TRAJECTORY_SECTIONS 50

#define MAP_WID 20.0f
#define MAP_HEI 20.0f
#define MAX_PLAYER_CNT 4
#define MAX_SHIP_CNT 1024
#define RENDER_INTERVAL 0.02f
#define RENDER_PER_TICK 25
#define TICK_STEP (RENDER_INTERVAL) * (RENDER_PER_TICK)

#endif