#ifndef CONSTANTS_H
#define CONSTANTS_h

#define WIN_WID 960
#define WIN_HEI 540
#define COLORS {RED, YELLOW, BLUE, GREEN}
#define PREDICT_TRAJECTORY_SIZE 0.03f
#define SHIP_RADIUS 0.1f
#define TRAJECTORY_SECTIONS 50
#define MINIMAP_POS_X 630
#define MINIMAP_POS_Y 20
#define MINIMAP_WID 260
#define MINIMAP_HEI 260

#define MAP_WID 20.0f
#define MAP_HEI 20.0f
#define MAX_PLAYER_CNT 4
#define MAX_SHIP_CNT 1024
#define RENDER_INTERVAL 0.01f
#define RENDER_PER_TICK 50
#define TICK_STEP (RENDER_INTERVAL) * (RENDER_PER_TICK)

#endif